language: ruby
rvm:
  - 2.4.1

script: echo "mdc"

branches:
  only:
  - master

sudo: false

cache: bundler

# yah no more pllllleaseeeee
notifications:
  email:
    on_success: never
    on_failure: never
